version: "3.9"
services:
  api:
    image: ksugimori/minesweeper-server
    container_name: ms-api
    ports:
      - 80:3000

  db:
    image: mysql:8.0
    container_name: ms-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: minesweeper
      MYSQL_USER: ms-user
      MYSQL_PASSWORD: ms-password
    volumes:
      - ms-db-volume:/var/lib/mysql

volumes:
  ms-db-volume:
    