CREATE TABLE cells (
  gameId INT NOT NULL,
  x INT NOT NULL,
  y INT NOT NULL,
  count TINYINT NOT NULL DEFAULT(0),
  isMine BOOLEAN NOT NULL DEFAULT(FALSE),
  isOpen BOOLEAN NOT NULL DEFAULT(FALSE),
  isFlag BOOLEAN NOT NULL DEFAULT(FALSE),
  PRIMARY KEY (gameId, x, y),
  FOREIGN KEY parent (gameId) REFERENCES games (id) ON DELETE CASCADE
);